/* ════════════════════════════════════════════════════════
   CONFIG.JS — Toutes les données et traductions du site
   Modifiez ce fichier pour changer les textes, images, etc.
════════════════════════════════════════════════════════ */

/* ─── IMAGES ─── */
export const IMAGES = {
  heroAlt: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?crop=entropy&cs=srgb&fm=jpg&w=2400&q=85",
  baijiuPour: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  wineBottle: "https://images.unsplash.com/photo-1670065921509-d0e0d053355b?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  wineClass: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  gala: "https://images.unsplash.com/photo-1580657274234-7339717f4541?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  wineCellar: "https://images.unsplash.com/photo-1684606308245-a4784b99cea2?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  parisHotel: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  flowers: "https://images.unsplash.com/photo-1540541338287-41700207dee6?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  city: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  champagneHouse: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  bordeauxChateau: "https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  gallery: "https://images.unsplash.com/photo-1655205145442-84abe0ae4fab?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  privateDinner: "https://images.unsplash.com/photo-1778504251906-3a92a67dc4c9?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  tasting: "https://images.unsplash.com/photo-1773113634646-953447d509d9?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  cultural: "https://images.unsplash.com/photo-1545048702-79362596cdc9?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  vineyard: "https://images.unsplash.com/photo-1726981897998-e9e7d981e26a?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  meeting: "https://images.unsplash.com/photo-1492447273231-0f8fecec1e3a?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  showroom: "https://images.unsplash.com/photo-1568526381923-caf3fd520382?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  museum: "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
};

/* ─── IMAGES BOUTEILLES ─── */
const IMG = (id) => `https://images.unsplash.com/photo-${id}?crop=entropy&cs=srgb&fm=jpg&w=1600&q=85`;
export const POOL_B = {
  bottleA: IMG("1670065921509-d0e0d053355b"),
  bottleB: IMG("1724878053340-5658df96b2a6"),
  bottleC: IMG("1688435526858-f8a548c694c7"),
  bottleD: IMG("1678062644165-7946d881d49b"),
  bottleE: IMG("1678062644184-6fde1896f69d"),
  bottleF: IMG("1547595628-c61a29f496f0"),
  bottleG: IMG("1684606308245-a4784b99cea2"),
  bottleH: IMG("1726981897998-e9e7d981e26a"),
};
export const POOL_W = {
  bottleA: IMG("1670065921509-d0e0d053355b"),
  bottleB: IMG("1547595628-c61a29f496f0"),
  bottleC: IMG("1474722883778-792e7990302f"),
  bottleD: IMG("1510972527921-ce03766a1cf1"),
  bottleE: IMG("1506377247377-2a5b3b417ebb"),
  bottleF: IMG("1773113634646-953447d509d9"),
};

/* ─── CONTACT ─── */
export const CONTACT = {
  email: "contact@c-prestige.com",
  address: "76 boulevard Haussmann\n75008 Paris",
  addressHtml: "76 boulevard Haussmann<br />75008 Paris",
  instagram: "#",
  linkedin: "#",
};

/* ─── TRADUCTIONS ─── */
export const T = {
fr: {
  nav: {
    home: "Accueil", who: "La Maison", baijiu: "Baijiu",
    wine: "Vin Chinois", expositions: "Expositions",
    academie: "Académie", events: "Événements",
    contact: "Contact", ctaB2C: "Découvrir la Maison", ctaB2B: "Devenir partenaire",
  },
  home: {
    overline: "Paris · Pékin · Shanghai",
    headline: "La Maison du Baijiu & du vin chinois à Paris.",
    subhead: "La porte d'entrée des marques chinoises de luxe en Europe.",
    ctaB2C: "Découvrir la Maison", ctaB2B: "Devenir partenaire", scroll: "Défiler",
    authorityOverline: "L'art du pont culturel",
    authorityTitle: "Une maison à la croisée de deux civilisations du goût.",
    authorityBullets: [
      "Basée à Paris",
      "Expertise biculturelle, équipe bilingue",
      "Réseau hôtelier & luxe français",
      "Spécialistes d'événements & d'expositions",
      "Conseil en entrée de marché Europe",
    ],
    journeysOverline: "Deux voies, une signature",
    journeysTitle: "Choisissez votre parcours.",
    journeyB2C: {
      kicker: "Pour les amateurs · B2C",
      title: "Découvrir le Baijiu, le vin chinois et la culture millénaire.",
      body: "Dégustations privées, Expositions culturelles, soirées intimes — la Chine du goût, dévoilée à Paris.",
      cta: "Explorer les Expositions",
    },
    journeyB2B: {
      kicker: "Pour les marques · B2B",
      title: "Implanter votre maison en France et en Europe.",
      body: "Lancements à Paris, expositions, mise en réseau, positionnement luxe — un accompagnement de bout en bout.",
      cta: "Voir nos services",
    },
    previewsOverline: "L'univers",
    previewsTitle: "Quatre territoires d'excellence.",
    previews: [
      { tag: "I",   title: "Baijiu",            desc: "L'esprit national chinois, célébré à Paris.",           to: "/baijiu" },
      { tag: "II",  title: "Vin chinois",        desc: "Terroirs rares, cuvées d'exception.",                   to: "/chinese-wine" },
      { tag: "III", title: "Prestige Académie",  desc: "Master Classes de Bordeaux & champagne.",               to: "/prestige-academie" },
      { tag: "IV",  title: "Événements & Conseil", desc: "Lancements, expositions, entrée de marché.",          to: "/events" },
    ],
    partnershipOverline: "Partenariats",
    partnershipTitle: "Hôtels, maisons de luxe, distilleries, domaines viticoles — rejoignez notre cercle.",
    partnershipBody: "Nous sélectionnons un nombre restreint de partenaires européens et chinois pour composer ensemble des moments rares.",
    partnershipCta: "Initier la conversation",
  },
  who: {
    overline: "La Maison",
    title: "Le pont entre la Chine du luxe et l'Europe.",
    lead: "Capital Prestige est née d'une conviction : la grande culture chinoise du Baijiu et du vin mérite, à Paris, une maison digne de son héritage.",
    story1Title: "Une origine bilingue.",
    story1: "Fondée par une équipe franco-chinoise du luxe et de l'hôtellerie, notre maison opère depuis Paris pour servir deux mondes : les clients européens curieux de l'art chinois du goût, et les marques chinoises désireuses de s'implanter dignement en Europe.",
    story2Title: "Un réseau, une promesse.",
    story2: "Hôtels palaces, salons privés, distilleries d'exception, vignerons, conservateurs, journalistes — nous orchestrons les rencontres qui font naître les grandes histoires de marque.",
    valuesOverline: "Valeurs",
    values: [
      { title: "Biculturalité", desc: "Nous parlons les deux langues — la française et la chinoise — du commerce, de l'art et de l'élégance." },
      { title: "Discrétion",    desc: "Nos relations se forment en privé. Vos noms ne quittent jamais nos salons." },
      { title: "Excellence",    desc: "Chaque détail est composé jusqu'au seuil de la perfection." },
      { title: "Réseau",        desc: "Paris, Hong Kong, Shanghai, Pékin — un carnet d'adresses choisi avec soin." },
    ],
  },
  baijiu: {
    overline: "Baijiu · 白酒",
    title: "La Maison du Baijiu à Paris.",
    lead: "Le Baijiu est l'esprit le plus consommé au monde. À Paris, nous lui offrons une scène à sa hauteur.",
    sections: [
      { kicker: "Héritage",  title: "Mille ans dans une goutte.",         body: "Du Sichuan au Guizhou — patrie de Moutai (茅台) — le Baijiu naît du sorgho rouge, des qū anciens, des caves de terre. Une alchimie qui défie toute comparaison." },
      { kicker: "Maisons",   title: "Moutai, Wuliangye, Luzhou Laojiao.", body: "Les grandes distilleries de Chine s'inscrivent dans une tradition millénaire. Sauce, fort, léger, doux : chaque famille raconte une géographie, une école artisanale. Nous vous initions à leur lecture." },
      { kicker: "À Paris",   title: "Dégustations, accords, rituels.",    body: "Verticales d'exception, accords mets-Baijiu signés par des chefs étoilés, salons privés dans nos adresses de confiance." },
    ],
    offeringsOverline: "Nos propositions",
    offerings: [
      { title: "Dégustation privée",       desc: "Une initiation guidée à travers cinq Baijiu d'exception, en salon privé parisien." },
      { title: "Accords gastronomiques",   desc: "Un menu en quatre temps composé avec un chef étoilé autour de bouteilles rares." },
      { title: "Cellier d'investissement", desc: "Conseil en constitution de cave : pièces de collection, années, rareté." },
    ],
    mapOverline: "Carte des terroirs",
    mapTitle: "Les douze provinces du Baijiu.",
    flavorsOverline: "Les 12 saveurs · Xiang",
  },
  wine: {
    overline: "Vin Chinois · 中国葡萄酒",
    title: "La Maison du vin chinois à Paris.",
    lead: "La Chine compte aujourd'hui parmi les grands pays vignerons du monde. Nous en révélons les terroirs.",
    sections: [
      { kicker: "Terroirs", title: "Ningxia, Shandong, Yunnan.",       body: "Des altitudes himalayennes aux collines de Penglai, de jeunes domaines composent une nouvelle géographie du vin de qualité." },
      { kicker: "Maisons",  title: "Changyu, Grace Vineyard, Ao Yun.", body: "De l'institution centenaire Changyu au domaine LVMH du Yunnan Ao Yun, les grandes maisons viticoles chinoises s'imposent face aux classiques européens." },
      { kicker: "À Paris",  title: "Dégustations comparées.",          body: "Nous organisons des dégustations où les meilleurs vins chinois rencontrent en face à face leurs équivalents français." },
    ],
    offeringsOverline: "Nos propositions",
    offerings: [
      { title: "Verticale comparée", desc: "Animée par un Master Sommelier français, un cépage, deux origines : Chine vs France." },
      { title: "Soirée domaine",     desc: "Un vigneron chinois invité à Paris pour présenter ses cuvées devant un cercle restreint." },
      { title: "Sélection privée",   desc: "Pour un particulier ou une institution, composer une cave de vins chinois rares." },
    ],
    mapOverline: "Carte viticole de Chine",
    mapTitle: "Douze régions, douze terroirs.",
  },
  expositions: {
    overline: "Expositions privées",
    title: "Le goût, dans sa plus originelle intimité.",
    lead: "Pour quelques-uns, des moments composés à la main. Pas un programme, pas un menu — une séquence.",
    items: [
      { kicker: "Chapitre I",   title: "Dîner privé.",        body: "Un chef étoilé à votre table. Un menu conçu autour d'une bouteille rare. Quatre couverts, parfois six." },
      { kicker: "Chapitre II",  title: "Dégustation guidée.", body: "Cinq Baijiu, cinq verres, une heure de narration. La Chine du goût, déroulée comme un poème." },
      { kicker: "Chapitre III", title: "Cadeau culturel.",    body: "Cérémonie du thé impérial, nuit de calligraphie, soirée poétique : la Chine dans ses couches les plus subtiles." },
      { kicker: "Chapitre IV",  title: "Voyage d'exception.", body: "Sur invitation : une semaine entre Ningxia et Shanghai, à visiter des domaines inaccessibles au commun." },
    ],
  },
  events: {
    overline: "Événements & Conseil B2B",
    title: "Pour les marques chinoises qui entrent en Europe.",
    lead: "Capital Prestige opère comme une maison de conseil luxe : nous vous ouvrons Paris — et, par extension, l'Europe.",
    challengeTitle: "Le marché européen, en cinq défis.",
    challenges: [
      { tag: "01", title: "Les codes culturels.", body: "Les codes du luxe européen ne se traduisent pas — ils se vivent. Nous traduisons votre marque dans la grammaire locale." },
      { tag: "02", title: "La distribution.",     body: "Cavistes fine wine, palaces, restaurants Michelin : un écosystème exigeant et fermé. Nous l'ouvrons." },
      { tag: "03", title: "La visibilité.",        body: "Une marque inconnue à Paris est une marque silencieuse. Nous orchestrons votre voix." },
      { tag: "04", title: "Les réseaux.",          body: "Influenceurs, journalistes, collectionneurs, critiques : nous vous présentons aux bonnes personnes." },
      { tag: "05", title: "Le positionnement.",   body: "Le luxe n'est pas un prix — c'est un récit. Nous construisons le vôtre." },
    ],
    servicesOverline: "Nos services d'entrée de marché",
    services: [
      { title: "Lancement de marque à Paris",      desc: "Soirées de lancement dans des adresses signatures : palaces, hôtels particuliers, fondations." },
      { title: "Dégustations acheteurs",           desc: "Sessions privées avec cavistes, sommeliers, importateurs et chefs étoilés." },
      { title: "Expositions & vitrines culturelles", desc: "Mise en scène de votre héritage dans des lieux parisiens d'art et de culture." },
      { title: "Introductions ciblées",            desc: "Rencontres orchestrées avec critiques, influenceurs, collectionneurs et journalistes." },
      { title: "Positionnement stratégique",       desc: "Narrative de marque, identité, prix, distribution : un accompagnement complet." },
    ],
    processOverline: "Notre méthode",
    processTitle: "Trois mouvements, une signature.",
    process: [
      { num: "I",   title: "Diagnostic.",  body: "Audit de votre marque, de votre narrative et de votre fit avec le marché européen." },
      { num: "II",  title: "Composition.", body: "Stratégie sur mesure, plan événementiel, sélection de partenaires, calendrier d'apparitions." },
      { num: "III", title: "Exécution.",   body: "Production événementielle, relations presse, suivi post-événement, indicateurs clés." },
    ],
    brandsOverline: "Nous servons",
    brandsTitle: "Distilleries de Baijiu, domaines viticoles, maisons de luxe, marques d'art de vivre.",
    brandsCta: "Construire votre arrivée en Europe",
  },
  academie: {
    overline: "Prestige Académie",
    brandName: "云酿-范儿 · Prestige Académie",
    title: "Explorer le monde du vin.",
    lead: "Le canal académique de Capital Prestige, dédié à transmettre la grande culture du vin à un public exigeant en Chine et en Europe.",
    videoOverline: "Master Classes",
    masterClassTitle: "Master Class Grand Cru de Bordeaux.",
    masterClassBody: "Une série filmée en compagnie des plus grandes maisons : du Médoc aux Graves, du champagne au Sauternes. Chaque épisode est une leçon — par les vignerons, pour les passionnés.",
    episodes: [
      { tag: "Épisode I",   title: "Moët & Chandon — Épernay.",       host: "Maison de Champagne",           body: "Au cœur du plus grand vignoble de Champagne, une leçon sur l'assemblage, le dosage et l'art de la bulle." },
      { tag: "Épisode II",  title: "Moët & Chandon — Suite.",          host: "Maison de Champagne",           body: "De la vendange au chai : la patience comme matière première, la précision comme signature." },
      { tag: "Épisode III", title: "Château Smith Haut Lafitte.",      host: "Pessac-Léognan, Grand Cru Classé", body: "Un Grand Cru biologique : terroirs de graves, vinification précise, domaine entièrement consacré à l'excellence." },
    ],
    lbbcOverline: "Left Bank Bordeaux Cup",
    lbbcTitle: "La compétition internationale de dégustation des clubs universitaires.",
    lbbcBody: "Organisé par la Commanderie du Bontemps de Bordeaux, le LBBC est un concours de dégustation à l'aveugle réservé aux clubs de vin des meilleures universités mondiales. Une scène où la prochaine génération de passionnés de Bordeaux se révèle.",
    lbbcStats: [
      { num: "50+",      label: "Universités participantes" },
      { num: "20",       label: "Pays représentés" },
      { num: "Bordeaux", label: "Finale annuelle" },
    ],
    ctaWatch: "Voir sur YouTube",
    ctaJoin: "Rejoindre l'Académie",
    youtubeUrl: "https://www.youtube.com/channel/UCDViqzQ1up0WuJxD-lN2Sdw",
  },
  contact: {
    overline: "Contact",
    title: "Un accès réservé à une clientèle sélectionnée.",
    lead: "Que vous soyez connaisseur ou marque, chaque demande est lue personnellement. Réponse sous 48 heures.",
    sidebarTitle: "La Maison",
    sidebarBody: "76 boulevard Haussmann, 75008 Paris.",
    sidebarEmail: "contact@c-prestige.com",
    sidebarHours: "Ligne privée — Réponse sous 48 h",
    emailCta: "Écrire à la Maison",
    emailLabel: "Pour toute demande privée ou partenariat, écrivez-nous directement.",
  },
  footer: {
    tagline: "La Maison du Baijiu & du vin chinois à Paris.",
    navTitle: "Navigation",
    contactTitle: "Contacts discrets",
    copy: "© Capital Prestige — Tous droits réservés",
    legal: "Biculturalité · Discrétion · Excellence",
  },
},

en: {
  nav: {
    home: "Home", who: "The House", baijiu: "Baijiu",
    wine: "Chinese Wine", expositions: "expositions",
    academie: "Academy", events: "Events & Advisory",
    contact: "Contact", ctaB2C: "Discover the House", ctaB2B: "Become a partner",
  },
  home: {
    overline: "Paris · Beijing · Shanghai",
    headline: "The House of Baijiu & Chinese Wine in Paris.",
    subhead: "The gateway for Chinese luxury brands into Europe.",
    ctaB2C: "Discover the House", ctaB2B: "Become a partner", scroll: "Scroll",
    authorityOverline: "The art of the cultural bridge",
    authorityTitle: "A house at the crossroads of two civilisations of taste.",
    authorityBullets: [
      "Based in Paris",
      "Bicultural expertise, bilingual team",
      "French hotel & luxury network",
      "Event & exhibition specialists",
      "Market entry advisory for Europe",
    ],
    journeysOverline: "Two paths, one signature",
    journeysTitle: "Choose your journey.",
    journeyB2C: {
      kicker: "For connoisseurs · B2C",
      title: "Discover Baijiu, Chinese wine and a millenial culture.",
      body: "Private tastings, cultural expositions, intimate evenings — the taste of China, unveiled in Paris.",
      cta: "Explore expositions",
    },
    journeyB2B: {
      kicker: "For brands · B2B",
      title: "Establish your house in France and Europe.",
      body: "Paris launches, exhibitions, networking, luxury positioning — end-to-end support.",
      cta: "See our services",
    },
    previewsOverline: "Our universe",
    previewsTitle: "Four territories of excellence.",
    previews: [
      { tag: "I",   title: "Baijiu",          desc: "China's national spirit, celebrated in Paris.",  to: "/baijiu" },
      { tag: "II",  title: "Chinese Wine",    desc: "Rare terroirs, exceptional vintages.",            to: "/chinese-wine" },
      { tag: "III", title: "Prestige Academy",desc: "Bordeaux & Champagne Master Classes.",            to: "/prestige-academie" },
      { tag: "IV",  title: "Events & Advisory",desc: "Launches, exhibitions, market entry.",           to: "/events" },
    ],
    partnershipOverline: "Partnerships",
    partnershipTitle: "Hotels, luxury houses, distilleries, vineyards — join our circle.",
    partnershipBody: "We select a limited number of European and Chinese partners to craft rare moments together.",
    partnershipCta: "Start the conversation",
  },
  who: {
    overline: "The House",
    title: "The bridge between luxury China and Europe.",
    lead: "Capital Prestige was born from a conviction: the great Chinese culture of Baijiu and wine deserves, in Paris, a house worthy of its heritage.",
    story1Title: "A bilingual origin.",
    story1: "Founded by a Franco-Chinese team from luxury and hospitality, our house operates from Paris to serve two worlds: European clients curious about the Chinese art of taste, and Chinese brands wishing to establish themselves with dignity in Europe.",
    story2Title: "A network, a promise.",
    story2: "Palace hotels, private salons, exceptional distilleries, winemakers, curators, journalists — we orchestrate the encounters that give birth to great brand stories.",
    valuesOverline: "Values",
    values: [
      { title: "Biculturality", desc: "We speak both languages — French and Chinese — of commerce, art and elegance." },
      { title: "Discretion",    desc: "Our relationships are formed in private. Your names never leave our salons." },
      { title: "Excellence",    desc: "Every detail is composed to the threshold of perfection." },
      { title: "Network",       desc: "Paris, Hong Kong, Shanghai, Beijing — a carefully selected address book." },
    ],
  },
  baijiu: {
    overline: "Baijiu · 白酒",
    title: "The House of Baijiu in Paris.",
    lead: "Baijiu is the most consumed spirit in the world. In Paris, we give it a stage worthy of its stature.",
    sections: [
      { kicker: "Heritage", title: "A thousand years in a drop.",          body: "From Sichuan to Guizhou — home of Moutai (茅台) — Baijiu is born of red sorghum, ancient qū cultures, and earth cellars. An alchemy that defies comparison." },
      { kicker: "Houses",   title: "Moutai, Wuliangye, Luzhou Laojiao.",  body: "China's great distilleries are rooted in a millennial tradition. Sauce, strong, light, rice: each family tells a geography, a craft school. We initiate you into their reading." },
      { kicker: "In Paris", title: "Tastings, pairings, rituals.",         body: "Exceptional verticals, Baijiu-food pairings signed by Michelin chefs, private salons in our trusted addresses." },
    ],
    offeringsOverline: "Our offerings",
    offerings: [
      { title: "Private tasting",    desc: "A guided initiation through five exceptional Baijiu, in a Parisian private salon." },
      { title: "Gastronomic pairings", desc: "A four-course menu composed with a Michelin chef around rare bottles." },
      { title: "Investment cellar",  desc: "Advisory on cellar building: collector's pieces, vintages, rarity." },
    ],
    mapOverline: "Terroir map",
    mapTitle: "The twelve provinces of Baijiu.",
    flavorsOverline: "The 12 aromas · Xiang",
  },
  wine: {
    overline: "Chinese Wine · 中国葡萄酒",
    title: "The House of Chinese Wine in Paris.",
    lead: "China now ranks among the world's great wine-producing nations. We reveal its terroirs.",
    sections: [
      { kicker: "Terroirs", title: "Ningxia, Shandong, Yunnan.",      body: "From Himalayan altitudes to the Penglai hills, young estates are composing a new geography of quality wine." },
      { kicker: "Houses",   title: "Changyu, Grace Vineyard, Ao Yun.", body: "From the century-old institution Changyu to LVMH's Yunnan domain Ao Yun, China's great wine houses now stand beside the European classics." },
      { kicker: "In Paris", title: "Comparative tastings.",            body: "We organise tastings where the best Chinese wines meet their French counterparts face to face." },
    ],
    offeringsOverline: "Our offerings",
    offerings: [
      { title: "Comparative vertical", desc: "Led by a French Master Sommelier, one grape variety, two origins: China vs France." },
      { title: "Estate evening",       desc: "A Chinese winemaker invited to Paris to present their wines to a select circle." },
      { title: "Private selection",    desc: "For an individual or institution, composing a cellar of rare Chinese wines." },
    ],
    mapOverline: "China wine map",
    mapTitle: "Twelve regions, twelve terroirs.",
  },
  expositions: {
    overline: "Private expositions",
    title: "Taste, in its most original intimacy.",
    lead: "For a few, moments composed by hand. Not a programme, not a menu — a sequence.",
    items: [
      { kicker: "Chapter I",   title: "Private dinner.",   body: "A Michelin chef at your table. A menu conceived around a rare bottle. Four covers, sometimes six." },
      { kicker: "Chapter II",  title: "Guided tasting.",   body: "Five Baijiu, five glasses, one hour of narration. The taste of China, unfolding like a poem." },
      { kicker: "Chapter III", title: "Cultural gift.",    body: "Imperial tea ceremony, calligraphy evening, poetry night: China in its most subtle layers." },
      { kicker: "Chapter IV",  title: "Exceptional journey.", body: "By invitation: a week between Ningxia and Shanghai, visiting estates inaccessible to the public." },
    ],
  },
  events: {
    overline: "Events & B2B Advisory",
    title: "For Chinese brands entering Europe.",
    lead: "Capital Prestige operates as a luxury consulting house: we open Paris to you — and Europe, by extension.",
    challengeTitle: "The European market, in five challenges.",
    challenges: [
      { tag: "01", title: "Cultural codes.", body: "European luxury codes are not translated — they are lived. We translate your brand into the local grammar." },
      { tag: "02", title: "Distribution.",   body: "Fine wine merchants, palaces, Michelin restaurants: a demanding, closed ecosystem. We open it." },
      { tag: "03", title: "Visibility.",     body: "An unknown brand in Paris is a silent brand. We orchestrate your voice." },
      { tag: "04", title: "Networks.",       body: "Influencers, journalists, collectors, critics: we introduce you to the right people." },
      { tag: "05", title: "Positioning.",    body: "Luxury is not a price — it is a narrative. We build yours." },
    ],
    servicesOverline: "Our market-entry services",
    services: [
      { title: "Brand launch in Paris",          desc: "Launch evenings in signature addresses: palaces, private mansions, foundations." },
      { title: "Buyer tastings",                 desc: "Private sessions with wine merchants, sommeliers, importers and Michelin chefs." },
      { title: "Exhibitions & cultural showcases", desc: "Staging of your heritage in Parisian art and culture venues." },
      { title: "Targeted introductions",         desc: "Orchestrated encounters with critics, influencers, collectors and journalists." },
      { title: "Strategic positioning",          desc: "Brand narrative, identity, pricing, distribution: a complete accompaniment." },
    ],
    processOverline: "Our method",
    processTitle: "Three movements, one signature.",
    process: [
      { num: "I",   title: "Diagnostic.",  body: "Audit of your brand, your narrative and your fit with the European market." },
      { num: "II",  title: "Composition.", body: "Tailored strategy, event plan, partner selection, appearances calendar." },
      { num: "III", title: "Execution.",   body: "Event production, press relations, post-event follow-up, key indicators." },
    ],
    brandsOverline: "We serve",
    brandsTitle: "Baijiu distilleries, vineyards, luxury houses, art-de-vivre brands.",
    brandsCta: "Build your European arrival",
  },
  academie: {
    overline: "Prestige Academy",
    brandName: "云酿-范儿 · Prestige Academy",
    title: "Explore the world of wine.",
    lead: "The academy channel of Capital Prestige, dedicated to transmitting the great culture of wine to a discerning audience in China and Europe.",
    videoOverline: "Master Classes",
    masterClassTitle: "Bordeaux Grand Cru Master Class.",
    masterClassBody: "A filmed series in the company of the greatest houses: from the Médoc to the Graves, from champagne to Sauternes. Each episode is a lesson — by the vignerons, for the passionate.",
    episodes: [
      { tag: "Episode I",   title: "Moët & Chandon — Épernay.",  host: "Champagne House",             body: "In the heart of Champagne's largest vineyard, a lesson on blending, dosage, and the art of the bubble." },
      { tag: "Episode II",  title: "Moët & Chandon — Continued.", host: "Champagne House",            body: "From harvest to cellar: patience as raw material, precision as signature." },
      { tag: "Episode III", title: "Château Smith Haut Lafitte.", host: "Pessac-Léognan, Grand Cru Classé", body: "An organic Grand Cru: gravel terroirs, precise vinification, and an estate fully devoted to excellence." },
    ],
    lbbcOverline: "Left Bank Bordeaux Cup",
    lbbcTitle: "The international tasting competition of university wine clubs.",
    lbbcBody: "Organised by the Commanderie du Bontemps of Bordeaux, the LBBC is a blind-tasting competition reserved for the wine clubs of the world's leading universities.",
    lbbcStats: [
      { num: "50+",      label: "Participating universities" },
      { num: "20",       label: "Countries represented" },
      { num: "Bordeaux", label: "Annual final" },
    ],
    ctaWatch: "Watch on YouTube",
    ctaJoin: "Join the Academy",
    youtubeUrl: "https://www.youtube.com/channel/UCDViqzQ1up0WuJxD-lN2Sdw",
  },
  contact: {
    overline: "Contact",
    title: "Access reserved for a selected clientele.",
    lead: "Whether you are a connoisseur or a brand, every request is read personally. Replies within 48 hours.",
    sidebarTitle: "The House",
    sidebarBody: "76 boulevard Haussmann, 75008 Paris.",
    sidebarEmail: "contact@c-prestige.com",
    sidebarHours: "Private line — Reply within 48 h",
    emailCta: "Write to the House",
    emailLabel: "For any private inquiry or partnership, write to us directly.",
  },
  footer: {
    tagline: "The House of Baijiu & Chinese Wine in Paris.",
    navTitle: "Navigation",
    contactTitle: "Discreet enquiries",
    copy: "© Capital Prestige — All rights reserved",
    legal: "Biculturality · Discretion · Excellence",
  },
},

zh: {
  nav: {
    home: "首页", who: "府邸", baijiu: "白酒",
    wine: "中国葡萄酒", expositions: "私享体验",
    academie: "学院", events: "活动与咨询",
    contact: "联系", ctaB2C: "探索府邸", ctaB2B: "成为合作伙伴",
  },
  home: {
    overline: "巴黎 · 北京 · 上海",
    headline: "巴黎的白酒与中国葡萄酒之家。",
    subhead: "中国奢侈品牌进入欧洲的门户。",
    ctaB2C: "探索府邸", ctaB2B: "成为合作伙伴", scroll: "向下浏览",
    authorityOverline: "文化之桥的艺术",
    authorityTitle: "立于两大味觉文明交汇处的府邸。",
    authorityBullets: [
      "立足巴黎",
      "双语双文化专长",
      "奢华酒店与款待网络",
      "活动与展览专家",
      "市场进入战略咨询",
    ],
    journeysOverline: "两条路径，一种品味",
    journeysTitle: "选择您的路径。",
    journeyB2C: {
      kicker: "致鉴赏者 · B2C",
      title: "在巴黎，品味白酒、中国葡萄酒与千年文化。",
      body: "私人品鉴、文化体验、亲密夜宴——中国的味觉之美，在巴黎展开。",
      cta: "探索体验",
    },
    journeyB2B: {
      kicker: "致品牌 · B2B",
      title: "在法国及欧洲，奠定贵府基石。",
      body: "巴黎首发、展览、社交、奢华定位——全方位陪伴。",
      cta: "查看服务",
    },
    previewsOverline: "我们的世界",
    previewsTitle: "四片卓越的领域。",
    previews: [
      { tag: "I",   title: "白酒",               desc: "中国国酒，于巴黎致敬。",       to: "/baijiu" },
      { tag: "II",  title: "中国葡萄酒",          desc: "稀有风土，卓越年份。",           to: "/chinese-wine" },
      { tag: "III", title: "Prestige Académie",  desc: "波尔多与香槟大师课。",           to: "/prestige-academie" },
      { tag: "IV",  title: "活动与咨询",          desc: "首发、展览、市场进入。",          to: "/events" },
    ],
    partnershipOverline: "合作伙伴",
    partnershipTitle: "酒店、奢华品牌、酒厂、葡萄园——加入我们的圈层。",
    partnershipBody: "我们精选少数欧洲与中国的合作伙伴，共谱稀有时刻。",
    partnershipCta: "开启对话",
  },
  who: {
    overline: "府邸",
    title: "连接中国奢华与欧洲的桥梁。",
    lead: "Capital Prestige 源于一种信念：中国白酒与葡萄酒的伟大文化，在巴黎，应有一座与其历史相称的府邸。",
    story1Title: "双语起源。",
    story1: "由来自奢华与款待业的中法团队创立，我们的府邸立足巴黎，服务两个世界：好奇于中国味觉艺术的欧洲客户，以及希望体面登陆欧洲的中国品牌。",
    story2Title: "一个网络，一个承诺。",
    story2: "宫殿酒店、私人沙龙、卓越的酒厂、酿酒师、策展人与记者——我们编织那些让伟大品牌故事得以诞生的相遇。",
    valuesOverline: "价值",
    values: [
      { title: "双文化", desc: "我们通晓两种语言——法语与中文——亦即商业、艺术与优雅的两种语言。" },
      { title: "低调",   desc: "我们的关系于私密中缔结。您的姓名不曾离开我们的沙龙。" },
      { title: "卓越",   desc: "每一处细节，皆雕琢至完美的边界。" },
      { title: "网络",   desc: "巴黎、香港、上海、北京——一本精心选录的通讯簿。" },
    ],
  },
  baijiu: {
    overline: "白酒",
    title: "巴黎的白酒之家。",
    lead: "白酒是世界上消费量最大的烈酒。在巴黎，我们为之奉上与之相称的舞台。",
    sections: [
      { kicker: "传承", title: "千年，凝于一滴。",       body: "由四川至贵州——茅台之乡——白酒生于红高粱、古曲与土窖。一种无可比拟的炼金术。" },
      { kicker: "名门", title: "茅台、五粮液、泸州老窖。", body: "中国伟大的酒厂承载千年传承。酱香、浓香、清香、米香：每一门类皆诉说一方地理、一所匠门。我们教您读懂。" },
      { kicker: "在巴黎", title: "品鉴、配餐、礼仪。",  body: "罕见垂直、米其林主厨签名的酒餐搭配、我们信赖的私密沙龙。" },
    ],
    offeringsOverline: "我们的方案",
    offerings: [
      { title: "私人品鉴", desc: "于巴黎私密沙龙中，引导您穿越五款卓越白酒。" },
      { title: "美馔搭配", desc: "与米其林主厨共构的四道菜单，围绕珍稀名酒展开。" },
      { title: "藏酒咨询", desc: "为您建构私窖：典藏之作、年份之选、稀有之珍。" },
    ],
    mapOverline: "风土地图",
    mapTitle: "白酒的十二个省份。",
    flavorsOverline: "十二种香型 · 香",
  },
  wine: {
    overline: "中国葡萄酒",
    title: "巴黎的中国葡萄酒之家。",
    lead: "中国今日已跻身全球大型酿酒国之列。我们揭示其风土。",
    sections: [
      { kicker: "风土", title: "宁夏、山东、云南。", body: "由喜马拉雅之高地到蓬莱之丘陵，年轻的酒庄正描绘一幅崭新的优质葡萄酒地理。" },
      { kicker: "名庄", title: "张裕、怡园、敖云。", body: "由百年张裕至 LVMH 旗下云南新庄敖云，中国伟大的葡萄酒名庄已与欧洲经典并肩。" },
      { kicker: "在巴黎", title: "稀世佳酿，比较之读。", body: "我们筹办品鉴会，让中国最佳葡萄酒与其法国同侪正面相遇。" },
    ],
    offeringsOverline: "我们的方案",
    offerings: [
      { title: "比较垂直", desc: "由法国侍酒大师领衔，一葡萄品种、中法两域之对照。" },
      { title: "酒庄之夜", desc: "邀请一位中国酿酒师莅临巴黎，向少数圈层呈现其佳酿。" },
      { title: "私人甄选", desc: "为个人或机构，构建一座中国稀世葡萄酒的酒窖。" },
    ],
    mapOverline: "中国葡萄酒地图",
    mapTitle: "十二个地区，十二种风土。",
  },
  expositions: {
    overline: "私享体验",
    title: "味觉，归于其最初的亲密。",
    lead: "为少数人，手工谱写的时刻。非课表、非菜单——而是瞬间。",
    items: [
      { kicker: "第一章", title: "私人晚宴。",  body: "一位米其林主厨亲临您的餐桌。一份围绕一瓶珍酿构思的菜单。四席，偶或六席。" },
      { kicker: "第二章", title: "引导品鉴。",  body: "五款白酒，五只杯盏，一段一小时的叙述。中国的味觉，如诗般铺陈。" },
      { kicker: "第三章", title: "文化之礼。",  body: "御茶之礼、书法之夜、诗歌之夕：中国文化最为精微的层次。" },
      { kicker: "第四章", title: "尊享之旅。",  body: "受邀而行：一周往返宁夏与上海，造访常人难入的酒庄与酒厂。" },
    ],
  },
  events: {
    overline: "活动与 B2B 咨询",
    title: "为进入欧洲的中国品牌而设。",
    lead: "Capital Prestige 如奢华咨询府邸般运作：我们为您打开巴黎——并由此延伸至整个欧洲。",
    challengeTitle: "欧洲市场，五重挑战。",
    challenges: [
      { tag: "01", title: "文化密码。", body: "欧洲奢华的密码非翻译可得——而是亲身体悟。我们将贵品牌译入当地的语法。" },
      { tag: "02", title: "分销渠道。", body: "高端酒商、宫殿酒店、米其林餐厅：一座苛严而封闭的生态。我们为您开启。" },
      { tag: "03", title: "可见性。",   body: "在巴黎，一座默默无闻的品牌即一座沉默的品牌。我们为您协调发声。" },
      { tag: "04", title: "人脉。",     body: "意见领袖、记者、收藏家、评论家：我们为您引见恰当之人。" },
      { tag: "05", title: "定位。",     body: "奢华非价格——而是叙事。我们为您构筑。" },
    ],
    servicesOverline: "我们的市场进入服务",
    services: [
      { title: "巴黎品牌首发",   desc: "于宫殿酒店、私邸与基金会等标志性地标举办首发之夜。" },
      { title: "买手品鉴",       desc: "与酒商、侍酒师、进口商及米其林主厨进行的私密会面。" },
      { title: "展览与文化展示", desc: "于巴黎艺术与文化场馆，呈现贵府的传承。" },
      { title: "精准引荐",       desc: "与评论家、意见领袖、收藏家及记者的精心安排之会。" },
      { title: "战略定位",       desc: "品牌叙事、识别、定价、分销：全方位陪伴。" },
    ],
    processOverline: "我们的方法",
    processTitle: "三个乐章，一种品味。",
    process: [
      { num: "I",   title: "诊断。", body: "审计贵品牌、贵叙事，以及与欧洲市场之契合度。" },
      { num: "II",  title: "构思。", body: "量身定制之战略、活动方案、合作伙伴遴选、亮相日程。" },
      { num: "III", title: "执行。", body: "活动制作、媒体关系、活动后跟进、关键指标。" },
    ],
    brandsOverline: "我们服务",
    brandsTitle: "白酒酒厂、葡萄酒庄、奢华府邸、生活艺术品牌。",
    brandsCta: "构建您的欧洲登陆",
  },
  academie: {
    overline: "Prestige Académie",
    brandName: "云酿-范儿 · Prestige Académie",
    title: "探索葡萄酒的世界。",
    lead: "Capital Prestige 的学院频道，致力于在中欧之间，向严苛的鉴赏者传递伟大的葡萄酒文化。",
    videoOverline: "大师课",
    masterClassTitle: "波尔多列级名庄大师课。",
    masterClassBody: "一部由名庄掌门人主讲的纪实系列：从梅多克到格拉夫，从香槟至苏玳。每一集都是一堂课——由酿造者亲授，为热爱者而设。",
    episodes: [
      { tag: "第一集", title: "酩悦香槟 · 埃佩尔奈。",  host: "香槟酒庄",       body: "于香槟区最辽阔的葡萄园之中，一堂关于调配、补液与气泡之道的课程。" },
      { tag: "第二集", title: "酩悦香槟 · 续。",         host: "香槟酒庄",       body: "由采收至酒窖：以耐心为原料，以精准为标记。" },
      { tag: "第三集", title: "史密斯拉菲特酒庄。",      host: "佩萨克-雷奥良，列级名庄", body: "一座有机列级名庄：砾石风土、精准酿造，整座酒庄全心倾注于卓越。" },
    ],
    lbbcOverline: "Left Bank Bordeaux Cup",
    lbbcTitle: "全球大学葡萄酒社团国际盲品大赛。",
    lbbcBody: "由波尔多 Commanderie du Bontemps 主办，LBBC 是面向全球顶尖大学葡萄酒社团的盲品比赛。",
    lbbcStats: [
      { num: "50+",  label: "参赛大学" },
      { num: "20",   label: "代表国家" },
      { num: "波尔多", label: "年度决赛" },
    ],
    ctaWatch: "前往 YouTube 频道",
    ctaJoin: "加入学院",
    youtubeUrl: "https://www.youtube.com/channel/UCDViqzQ1up0WuJxD-lN2Sdw",
  },
  contact: {
    overline: "联系",
    title: "仅向精选客户开放。",
    lead: "无论您是鉴赏者或品牌，每份请求皆由专人阅读。48 小时内回复。",
    sidebarTitle: "府邸",
    sidebarBody: "巴黎 75008，奥斯曼大道 76 号。",
    sidebarEmail: "contact@c-prestige.com",
    sidebarHours: "私人专线 — 48 小时内回复",
    emailCta: "致信府邸",
    emailLabel: "如需私人垂询或洽谈合作，请直接致函。",
  },
  footer: {
    tagline: "巴黎的白酒与中国葡萄酒之家。",
    navTitle: "导航",
    contactTitle: "低调垂询",
    copy: "© Capital Prestige — 版权所有",
    legal: "双文化 · 低调 · 卓越",
  },
},
};
