/* ════════════════════════════════════════════════════════
   DATA.JS — Marques Baijiu, saveurs et régions viticoles
   Modifiez ce fichier pour ajouter/modifier des marques
════════════════════════════════════════════════════════ */
import { POOL_B, POOL_W } from './config.js';

/* ─── SAVEURS BAIJIU ─── */
export const FLAVORS = [
  { slug: "sauce-aroma",     name: "Sauce Aroma",     nameZh: "酱香型", description: "La saveur la plus complexe et la plus prestigieuse du Baijiu, née du Guizhou. Notes umami profondes, longueur en bouche soyeuse, vieillissement en jarre. Style emblématique de la maison Moutai.",       video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 51, y: 62, name: "Guizhou" } },
  { slug: "strong-aroma",    name: "Strong Aroma",    nameZh: "浓香型", description: "La famille la plus consommée en Chine. Fermentation en fosse de terre ancestrale. Bouquet fruité intense, finale ample. Wuliangye et Luzhou Laojiao en sont les maîtres incontestés.",                   video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 42, y: 53, name: "Sichuan" } },
  { slug: "light-aroma",     name: "Light Aroma",     nameZh: "清香型", description: "Pureté cristalline, fermentation en cuve de céramique. Notes florales et de céréales fraîches. Une élégance sobre, signature des grandes maisons du Shanxi.",                                              video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 57, y: 39, name: "Shanxi" } },
  { slug: "rice-aroma",      name: "Rice Aroma",      nameZh: "米香型", description: "Distillation à base de riz, traditionnelle dans le Guangxi. Douceur miellée, légèreté florale. Le plus accessible des Baijiu, parfait pour une initiation.",                                              video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 51, y: 72, name: "Guangxi" } },
  { slug: "phoenix-aroma",   name: "Phoenix Aroma",   nameZh: "凤香型", description: "Originaire du Shaanxi. Équilibre rare entre puissance et finesse, notes de fruits secs et de céréales rôties. Une signature aristocratique millénaire.",                                                  video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 51, y: 42, name: "Shaanxi" } },
  { slug: "mixed-aroma",     name: "Mixed Aroma",     nameZh: "兼香型", description: "Hybride des grandes familles Sauce et Strong. Complexité aromatique double, longueur exceptionnelle. Le Hubei en est le berceau moderne.",                                                                  video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 58, y: 50, name: "Hubei" } },
  { slug: "sesame-aroma",    name: "Sesame Aroma",    nameZh: "芝麻香型", description: "Style récent du Shandong, identifié dans les années 1950. Notes torréfiées de sésame, douceur grillée. Une rareté à part.",                                                                             video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 69, y: 43, name: "Shandong" } },
  { slug: "te-aroma",        name: "Te Aroma",        nameZh: "特香型", description: "L'exception du Jiangxi. Distillation à base de riz long, fermentation en pierre. Notes franches, finale propre.",                                                                                          video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 72, y: 65, name: "Jiangxi" } },
  { slug: "medicinal-aroma", name: "Medicinal Aroma", nameZh: "药香型", description: "Style ancestral du Guizhou. Macération de plantes médicinales traditionnelles dans le grain. Bouche profonde, persistante, presque thérapeutique.",                                                       video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 53, y: 65, name: "Guizhou (S)" } },
  { slug: "laobaigan-aroma", name: "Laobaigan Aroma", nameZh: "老白干香型", description: "Hebei, école classique du nord. Pureté minérale, sécheresse noble, droiture aromatique. L'ancêtre des styles «light».",                                                                              video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 63, y: 36, name: "Hebei" } },
  { slug: "chi-aroma",       name: "Chi Aroma",       nameZh: "豉香型", description: "Particulier au Guangdong. Macération de viande de porc séchée dans le distillat. Profondeur umami inattendue, identité radicalement asiatique.",                                                           video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 58, y: 73, name: "Guangdong" } },
  { slug: "fuyu-aroma",      name: "Fuyu Aroma",      nameZh: "馥郁香型", description: "Triple complexité — Sauce + Strong + Light en une seule bouche. Le Hunan a inventé un style à mi-chemin entre la richesse et la pureté.",                                                              video: "https://www.youtube.com/embed/dQw4w9WgXcQ", region: { x: 56, y: 62, name: "Hunan" } },
];

/* ─── MARQUES BAIJIU ─── */
export const BRANDS = [
  { slug: "kweichow-moutai",   name: "Kweichow Moutai",    flavor: "sauce-aroma",     image: POOL_B.bottleA, history: "Fondée en 1951 à Maotai (Guizhou), héritière d'une tradition impériale millénaire. Servie lors des grands sommets d'État chinois.",          description: "L'icône absolue du Baijiu. Une bouteille blanche frappée du sceau rouge, devenue le symbole national. Production limitée, vieillissement minimum cinq ans, finale soyeuse et complexe.",   style: "Sauce Aroma · vieillissement long en jarre de terre cuite" },
  { slug: "langjiu",           name: "Langjiu",             flavor: "sauce-aroma",     image: POOL_B.bottleB, history: "Distillée depuis le XIXᵉ siècle dans la vallée du Chishui, voisine de Moutai. Renommée pour ses caves naturelles creusées dans la falaise.",    description: "Le grand rival sage de Moutai, fidèle au même terroir mais à un style plus discret. Une école «sauce» à la fois rigoureuse et accessible.",                                                     style: "Sauce Aroma · caves de falaise, fermentation longue" },
  { slug: "wuliangye",         name: "Wuliangye",           flavor: "strong-aroma",    image: POOL_B.bottleC, history: "Yibin (Sichuan). Cinq céréales — sorgho, riz, riz gluant, maïs, blé — assemblées depuis le XIVᵉ siècle.",                                      description: "Le maître du Strong Aroma. Une fosse de fermentation ininterrompue depuis plus de six cents ans. Bouche puissante, fruité abondant.",                                                          style: "Strong Aroma · cinq céréales, fosse millénaire" },
  { slug: "luzhou-laojiao",    name: "Luzhou Laojiao",      flavor: "strong-aroma",    image: POOL_B.bottleD, history: "Luzhou (Sichuan), 1573. La plus ancienne fosse de fermentation continue au monde, classée patrimoine national.",                                   description: "La maison historique du Strong Aroma. Une signature dense, des arômes ronds, une persistance noble.",                                                                                          style: "Strong Aroma · fosse de 1573, encore en activité" },
  { slug: "fenjiu",            name: "Fenjiu",              flavor: "light-aroma",     image: POOL_B.bottleE, history: "Xinghuacun (Shanxi), distillé depuis plus de 1500 ans. Cité par les poètes Tang, immortalisé par Du Mu.",                                          description: "Le grand classique du Light Aroma. Cristallin, pur, fleurs blanches et grain frais. L'élégance du nord.",                                                                                     style: "Light Aroma · fermentation en cuve de céramique" },
  { slug: "red-star-erguotou", name: "Red Star Erguotou",   flavor: "light-aroma",     image: POOL_B.bottleF, history: "Pékin, 1949. Le Baijiu populaire de la capitale, fondé l'année de la République populaire.",                                                       description: "Un Erguotou direct, franc, sans détour — la signature du «deuxième passage». Le Baijiu de tous les Pékinois.",                                                                                 style: "Light Aroma · double distillation rapide" },
  { slug: "guilin-sanhua",     name: "Guilin Sanhua",       flavor: "rice-aroma",      image: POOL_B.bottleG, history: "Guilin (Guangxi), une tradition de mille ans dans la grotte de Xiangbi. Élaboré à base de riz local.",                                             description: "Le grand Baijiu de riz. Doux, miellé, floraux, parfait pour une initiation. Vieilli dans une grotte karstique.",                                                                               style: "Rice Aroma · grotte de Xiangbi, riz local" },
  { slug: "yulinquan",         name: "Yulinquan",           flavor: "rice-aroma",      image: POOL_B.bottleH, history: "Yulin (Guangxi). Une distillerie ancienne au sud-est, sublime expression du riz d'Asie tropicale.",                                                description: "Un Baijiu de riz d'une grande tendresse aromatique. Touches de fruit blanc et de miel d'acacia.",                                                                                              style: "Rice Aroma · riz tropical, fermentation lente" },
  { slug: "xifengjiu",         name: "Xifengjiu",           flavor: "phoenix-aroma",   image: POOL_B.bottleA, history: "Fengxiang (Shaanxi), distillé depuis la dynastie Tang. Servi à la cour impériale.",                                                                description: "La maison historique du Phoenix Aroma. Équilibre entre puissance et finesse, noyaux et fruits secs.",                                                                                          style: "Phoenix Aroma · jarres de tu (loess)" },
  { slug: "taibai-jiu",        name: "Taibai Jiu",          flavor: "phoenix-aroma",   image: POOL_B.bottleB, history: "Mei County (Shaanxi). Distillerie nommée d'après le poète Li Bai, immortel du vin chinois.",                                                      description: "Un Baijiu profondément littéraire, signé du poète Taibai. Aromatique, raffiné, élégant.",                                                                                                     style: "Phoenix Aroma · hommage poétique" },
  { slug: "baiyunbian",        name: "Baiyunbian",          flavor: "mixed-aroma",     image: POOL_B.bottleC, history: "Songzi (Hubei). Pionnier moderne du style «jian» (mélangé) depuis les années 1970.",                                                               description: "Marie la finesse Light à la profondeur Sauce. Une bouche en deux temps, longue et complexe.",                                                                                                  style: "Mixed Aroma · double fermentation" },
  { slug: "kouzijiao",         name: "Kouzijiao",           flavor: "mixed-aroma",     image: POOL_B.bottleD, history: "Bozhou (Anhui), héritière de la grande tradition du nord. Recettes datant de la dynastie Song.",                                                   description: "Mariage Sauce + Strong d'une grande harmonie. Texture soyeuse, finale délicate.",                                                                                                              style: "Mixed Aroma · double maturation" },
  { slug: "jingzhi-baijiu",    name: "Jingzhi Baijiu",      flavor: "sesame-aroma",    image: POOL_B.bottleE, history: "Anqiu (Shandong). Pionnier de l'identification scientifique du Sesame Aroma dans les années 1950.",                                                description: "Notes torréfiées de sésame doré, douceur grillée caractéristique. Une signature rare et identifiable.",                                                                                        style: "Sesame Aroma · arôme grillé fondateur" },
  { slug: "bandaojing",        name: "Bandaojing",          flavor: "sesame-aroma",    image: POOL_B.bottleF, history: "Gaomi (Shandong). Production artisanale réputée pour la pureté de son sésame aromatique.",                                                         description: "L'école élégante du sésame. Bouche ronde, persistance dorée, gastronomie naturelle.",                                                                                                          style: "Sesame Aroma · pureté torréfiée" },
  { slug: "site-jiu",          name: "Si'te Jiu",           flavor: "te-aroma",        image: POOL_B.bottleG, history: "Zhangshu (Jiangxi). Référence absolue du style Te depuis sa codification en 1988.",                                                               description: "Distillation de riz long, fermentation en cuve de pierre. Notes nettes, finale épurée.",                                                                                                       style: "Te Aroma · cuve de pierre, riz long" },
  { slug: "zhanggong",         name: "Zhanggong",           flavor: "te-aroma",        image: POOL_B.bottleH, history: "Yichun (Jiangxi). Maison artisanale dédiée à la pureté du Te Aroma.",                                                                             description: "Un Te d'une grande franchise. Texture cristalline, expression pure du grain.",                                                                                                                  style: "Te Aroma · franchise du riz" },
  { slug: "dongjiu",           name: "Dongjiu",             flavor: "medicinal-aroma", image: POOL_B.bottleA, history: "Zunyi (Guizhou). Distillation ancestrale enrichie de plantes médicinales, recette inchangée depuis 200 ans.",                                      description: "Baijiu «médicinal» emblématique. Notes d'herbes amères, profondeur quasi thérapeutique.",                                                                                                     style: "Medicinal Aroma · macération de plantes" },
  { slug: "gubao",             name: "Gubao",               flavor: "medicinal-aroma", image: POOL_B.bottleB, history: "Yunnan, distillerie classique fondée au XIXᵉ siècle. Recette d'herbes du Sud.",                                                                   description: "Médicinal d'une douceur surprenante, herbes fraîches et notes camphrées.",                                                                                                                     style: "Medicinal Aroma · herbes du Yunnan" },
  { slug: "hengshui-laobaigan",name: "Hengshui Laobaigan",  flavor: "laobaigan-aroma", image: POOL_B.bottleC, history: "Hengshui (Hebei). L'ancêtre du style «vieux blanc sec», documenté depuis la dynastie Han.",                                                       description: "Pureté minérale absolue, sécheresse noble, droiture aromatique. Le grand classique du nord.",                                                                                                  style: "Laobaigan Aroma · sécheresse noble" },
  { slug: "shanzhuang",        name: "Shanzhuang",          flavor: "laobaigan-aroma", image: POOL_B.bottleD, history: "Hebei. Maison rigoureuse, fidèle à la tradition Laobaigan.",                                                                                       description: "Profil minéral et droit, sans concession. Une école stricte et lumineuse.",                                                                                                                    style: "Laobaigan Aroma · école stricte" },
  { slug: "yu-bing-sha",       name: "Yu Bing Sha",         flavor: "chi-aroma",       image: POOL_B.bottleE, history: "Foshan (Guangdong). Style cantonais identifié dans les années 1950.",                                                                              description: "Distillat enrichi de viande de porc séchée. Umami profond, identité audacieuse.",                                                                                                              style: "Chi Aroma · macération de porc séché" },
  { slug: "shuangzheng",       name: "Shuangzheng",         flavor: "chi-aroma",       image: POOL_B.bottleF, history: "Guangzhou (Guangdong). Maison cantonaise spécialisée dans le Chi.",                                                                                description: "Une expression épurée du Chi, plus accessible mais d'une grande profondeur asiatique.",                                                                                                        style: "Chi Aroma · expression épurée" },
  { slug: "jiugui-jiu",        name: "Jiugui Jiu",          flavor: "fuyu-aroma",      image: POOL_B.bottleG, history: "Jishou (Hunan). Pionnier du Fuyu, codifié en 1998 comme style officiel.",                                                                          description: "Triple harmonie Sauce + Strong + Light. Complexité spectaculaire, finale somptueuse.",                                                                                                         style: "Fuyu Aroma · triple expression" },
  { slug: "xiangjiao",         name: "Xiangjiao",           flavor: "fuyu-aroma",      image: POOL_B.bottleH, history: "Hunan, distillerie moderne dédiée à l'expression Fuyu.",                                                                                           description: "Une lecture contemporaine du Fuyu. Précision, équilibre, longueur.",                                                                                                                            style: "Fuyu Aroma · lecture moderne" },
];

/* ─── RÉGIONS VITICOLES ─── */
export const REGIONS = [
  { slug: "xinjiang",        name: "Xinjiang",       nameZh: "新疆",           x: 16, y: 45, description: "Vastes étendues désertiques, vendanges tardives, cépages internationaux résistants aux écarts thermiques.", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "gansu",           name: "Gansu",           nameZh: "甘肃",           x: 38, y: 48, description: "Corridor du Hexi, sur la route de la soie. Terroirs anciens, vendanges à 1500 m d'altitude.",              video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "ningxia",         name: "Ningxia",         nameZh: "宁夏",           x: 46, y: 45, description: "Le Bordeaux chinois — vignobles d'altitude au pied des monts Helan, terroirs sablonneux et continentaux.", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "inner-mongolia",  name: "Inner Mongolia",  nameZh: "内蒙古",         x: 58, y: 32, description: "Steppes du Wuhai, vendanges en bord de désert. Cépages rustiques, vins puissants.",                        video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "yunnan",          name: "Yunnan",          nameZh: "云南（香格里拉）", x: 38, y: 72, description: "Vignobles d'altitude himalayenne, à 2 600 m. Le terroir extrême, royaume d'Ao Yun.",                    video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "beijing",         name: "Beijing",         nameZh: "北京",           x: 72, y: 38, description: "Vallée de Fangshan, vignobles péri-urbains. Histoire viticole du nord moderne.",                           video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "tianjin",         name: "Tianjin",         nameZh: "天津",           x: 75, y: 40, description: "Plaine côtière du Bohai. Berceau de Dynasty, l'une des plus anciennes maisons modernes.",                  video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "hebei",           name: "Hebei",           nameZh: "河北",           x: 69, y: 43, description: "Vallée de Huailai, altitude continentale. Lieu d'élection des cuvées d'auteur du nord.",                   video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "shanxi",          name: "Shanxi",          nameZh: "山西",           x: 62, y: 48, description: "Hauts plateaux du Loess. Terroirs minéraux, vins droits, climat semi-aride.",                              video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "henan",           name: "Henan",           nameZh: "河南",           x: 64, y: 55, description: "Cœur historique de la Chine. Terroirs centraux, mémoire viticole millénaire.",                             video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "shandong",        name: "Shandong",        nameZh: "山东（烟台）",   x: 78, y: 50, description: "Berceau historique du vin chinois moderne — collines de Penglai, climat maritime, terroirs argilo-calcaires.", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
  { slug: "liaoning",        name: "Liaoning",        nameZh: "辽宁",           x: 80, y: 33, description: "Vallée du Yalu, frontière coréenne. Climat continental tempéré par la mer.",                               video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
];

/* ─── MARQUES DE VIN ─── */
export const WINE_BRANDS = [
  { slug: "helan-qingxue",        name: "Helan Qingxue",            region: "ningxia",       image: POOL_W.bottleA, history: "Fondé en 2005 dans la région de Helan. Cuvée Jia Bei Lan élue meilleur vin chinois par Decanter en 2011.",            description: "L'icône du Ningxia. Cabernet Sauvignon et Marselan élevés en barriques françaises, vinifiés dans la rigueur bordelaise.", style: "Rouge structuré · Cabernet Sauvignon, Marselan" },
  { slug: "silver-heights",        name: "Silver Heights",            region: "ningxia",       image: POOL_W.bottleB, history: "Domaine familial fondé par Emma Gao, formée à Bordeaux. Première récolte 2007.",                                    description: "L'expression la plus précise du Ningxia. Vinifications artisanales, vendanges manuelles, signature claire et longue.",   style: "Rouge précis · Cabernet Sauvignon, Cabernet Gernischt" },
  { slug: "tiansai-vineyards",     name: "Tiansai Vineyards",         region: "xinjiang",      image: POOL_W.bottleC, history: "Tianshan, fondé en 2010. Vignobles à 800 m, climat extrême du nord-ouest.",                                         description: "Tiansai compose des vins d'une puissance solaire, cabernet et marselan élevés dans la rigueur internationale.",          style: "Rouge puissant · vendanges tardives" },
  { slug: "loulan-wine",           name: "Loulan Wine",               region: "xinjiang",      image: POOL_W.bottleD, history: "Inspiré du royaume perdu de Loulan, sur la route de la soie.",                                                     description: "Vins de terroir désertique, robustes et solaires. Une approche locale et puissante.",                                    style: "Rouge solaire · cépages internationaux" },
  { slug: "changyu-pioneer",       name: "Changyu Pioneer Wine",      region: "shandong",      image: POOL_W.bottleE, history: "Fondée en 1892 par Zhang Bishi à Yantai. La plus ancienne maison vinicole moderne de Chine.",                       description: "L'institution centenaire du vin chinois. Cuvées d'archive, marques historiques, héritage de plus de 130 ans.",           style: "Rouges et blancs classiques · héritage Bordeaux" },
  { slug: "great-wall-wine",       name: "Great Wall Wine",           region: "shandong",      image: POOL_W.bottleF, history: "Fondée en 1983, l'une des trois grandes maisons d'État du vin chinois.",                                           description: "Cuvées accessibles, présentes sur toutes les tables chinoises. Une signature populaire et fiable.",                      style: "Rouge accessible · grand volume" },
  { slug: "grace-vineyard",        name: "Grace Vineyard",            region: "hebei",         image: POOL_W.bottleA, history: "Fondée en 1997 par Chan Chun Keung. Pionnier du vin de qualité moderne en Chine.",                                 description: "Domaine d'auteur, vinifications précises, élevage en barriques. Cuvée Deep Blue saluée par la critique internationale.", style: "Rouge d'auteur · Marselan, Cabernet" },
  { slug: "huailai-amethyst",      name: "Huailai Amethyst Manor",    region: "hebei",         image: POOL_W.bottleB, history: "Domaine du nord, fondé sur des terroirs altitude.",                                                                description: "Une lecture moderne du Hebei. Cuvées élégantes, finales fraîches.",                                                     style: "Rouge frais · altitude continentale" },
  { slug: "rongzi-chateau",        name: "Rongzi Chateau",            region: "shanxi",        image: POOL_W.bottleC, history: "Chateau Rongzi, fondé sur les plateaux du Loess. Architecture inspirée du Médoc.",                                 description: "Le Shanxi en grand style. Cuvées denses, terroirs minéraux et continentaux.",                                            style: "Rouge dense · plateaux du Loess" },
  { slug: "yuhuang-winery",        name: "Yuhuang Winery",            region: "shanxi",        image: POOL_W.bottleD, history: "Domaine historique du Shanxi, lien avec la tradition viticole du nord.",                                           description: "Cuvées de caractère, fidèles à la minéralité du Loess.",                                                                style: "Rouge minéral · école stricte" },
  { slug: "chateau-hansen",        name: "Chateau Hansen",            region: "inner-mongolia", image: POOL_W.bottleE, history: "Premier grand domaine du Wuhai (Mongolie intérieure), fondé en 2001.",                                            description: "Vendanges en bord de désert, cuvées puissantes et solaires.",                                                           style: "Rouge robuste · désert du Wuhai" },
  { slug: "helan-mountain",        name: "Helan Mountain Winery",     region: "inner-mongolia", image: POOL_W.bottleF, history: "Implanté au pied des monts Helan côté Mongolie.",                                                                 description: "Une vision continentale et radicale du vin chinois. Cuvées denses, droites.",                                            style: "Rouge radical · vignobles d'altitude" },
  { slug: "mogao-winery",          name: "Mogao Winery",              region: "gansu",         image: POOL_W.bottleA, history: "Domaine du Hexi, nommé d'après les grottes de Mogao. Vignes plantées en 1981.",                                    description: "Vins du corridor de la soie. Cuvées historiques, hommages aux marchands antiques.",                                     style: "Rouge classique · vignes anciennes" },
  { slug: "zixuan-winery",         name: "Zixuan Winery",             region: "gansu",         image: POOL_W.bottleB, history: "Maison moderne du Gansu, vignobles à 1500 m.",                                                                    description: "Une approche contemporaine du corridor du Hexi.",                                                                        style: "Rouge frais · 1500 m d'altitude" },
  { slug: "ao-yun",                name: "Ao Yun",                    region: "yunnan",        image: POOL_W.bottleC, history: "Fondé en 2013 par Moët Hennessy à 2 600 m dans les contreforts himalayens. Le projet vinicole extrême du LVMH.",  description: "Le grand cru himalayen. Vinifications au village, élevage rigoureux, cuvée unique d'exception.",                         style: "Rouge d'altitude · Cabernet Sauvignon, Cabernet Franc" },
  { slug: "shangri-la-winery",     name: "Shangri-La Winery",         region: "yunnan",        image: POOL_W.bottleD, history: "Pionnier du vin tibétain. Vignobles à plus de 2 200 m, communautés locales.",                                     description: "Vins de très haute altitude, expression rare des terroirs du Mékong supérieur.",                                         style: "Rouge himalayen · haute altitude" },
  { slug: "huaxia-great-wall",     name: "Huaxia Great Wall",         region: "liaoning",      image: POOL_W.bottleE, history: "Branche orientale du groupe Great Wall, fondée dans le Liaoning.",                                                description: "Une lecture du vin chinois côté frontière coréenne. Cuvées équilibrées, fraîches.",                                      style: "Rouge équilibré · climat maritime" },
  { slug: "wuzhou-winery",         name: "Wuzhou Winery",             region: "liaoning",      image: POOL_W.bottleF, history: "Maison moderne du Liaoning, vignobles tempérés par la mer Jaune.",                                                description: "Vins de fraîcheur, élégance moderne du nord-est chinois.",                                                               style: "Rouge frais · Yalu, climat tempéré" },
  { slug: "dragon-seal-winery",    name: "Dragon Seal Winery",        region: "beijing",       image: POOL_W.bottleA, history: "Co-fondée en 1987 avec Pernod Ricard. Premier domaine sino-français de l'ère moderne.",                            description: "L'histoire pionnière du vin chinois moderne. Cuvées de référence, méthode bordelaise.",                                  style: "Rouge pionnier · méthode bordelaise" },
  { slug: "beijing-friendship",    name: "Beijing Friendship Winery", region: "beijing",       image: POOL_W.bottleB, history: "Vinification péri-urbaine, vallée de Fangshan.",                                                                  description: "Le vin de la capitale, populaire et abordable. Une signature historique du nord.",                                       style: "Rouge populaire · vallée de Fangshan" },
  { slug: "dynasty-wine",          name: "Dynasty Wine",              region: "tianjin",       image: POOL_W.bottleC, history: "Fondée en 1980 — coentreprise sino-française avec Rémy Martin. Pionnier absolu du vin chinois moderne.",           description: "L'icône du nord. Cuvées historiques, héritage international, présence dans tous les hôtels chinois.",                   style: "Rouge classique · héritage Rémy Martin" },
  { slug: "tianjin-wine-group",    name: "Tianjin Wine Group",        region: "tianjin",       image: POOL_W.bottleD, history: "Conglomérat viticole du Bohai. Plus grand groupe vinicole de Tianjin.",                                           description: "Cuvées populaires, distribution massive. Une école accessible.",                                                         style: "Rouge accessible · grand volume" },
  { slug: "domaine-franco-chinois",name: "Domaine Franco-Chinois",    region: "henan",         image: POOL_W.bottleE, history: "Co-fondé en 1981 avec l'aide du gouvernement français. Premier domaine collaboratif sino-français.",               description: "Mémoire vivante de la coopération viticole sino-française. Cuvées historiques classées.",                               style: "Rouge historique · pionnier sino-français" },
  { slug: "henan-minquan",         name: "Henan Minquan Winery",      region: "henan",         image: POOL_W.bottleF, history: "Domaine de la plaine centrale du Henan, héritage de l'agriculture viticole locale.",                               description: "Une lecture continentale du Henan. Cuvées rustiques, terroirs historiques.",                                             style: "Rouge rustique · plaine centrale" },
];

/* ─── BOUTEILLES DÉRIVÉES ─── */
export const BOTTLES = FLAVORS.flatMap((f) =>
  BRANDS.filter(b => b.flavor === f.slug).map(b => ({
    slug: `${b.slug}-flagship`,
    name: `${b.name} — Édition signature`,
    image: b.image,
    description: `La bouteille phare de la maison ${b.name}. Une lecture aboutie du style ${f.name}.`,
    shopUrl: "https://www.thebaijiucompany.com/",
    flavor: f.slug,
    brand: b.slug,
  }))
);
